// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBUIeLLk0x2mk_vJ4dWJODk6OVXofi-okU',
//     appId: '1:528452120632:web:9c71a53366a375da64b6cd',
//     messagingSenderId: '528452120632',
//     projectId: 'tsincoco',
//     authDomain: 'tsincoco.firebaseapp.com',
//     storageBucket: 'tsincoco.appspot.com',
//     measurementId: 'G-VP91LZK53Y',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB5bGmnKRxiTCM-9yDIKykxSTYeBK8AStA',
//     appId: '1:528452120632:android:e887491a06061ad264b6cd',
//     messagingSenderId: '528452120632',
//     projectId: 'tsincoco',
//     storageBucket: 'tsincoco.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAxw2W74oj3WgOmfomvyzpk9ZVqIb1uNtY',
//     appId: '1:528452120632:ios:c3fdf32921623bff64b6cd',
//     messagingSenderId: '528452120632',
//     projectId: 'tsincoco',
//     storageBucket: 'tsincoco.appspot.com',
//     iosBundleId: 'com.tsincoco',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAxw2W74oj3WgOmfomvyzpk9ZVqIb1uNtY',
//     appId: '1:528452120632:ios:2ef5ad54b15a287e64b6cd',
//     messagingSenderId: '528452120632',
//     projectId: 'tsincoco',
//     storageBucket: 'tsincoco.appspot.com',
//     iosBundleId: 'com.example.pickrewardapp',
//   );
// }
